import 'package:flutter/material.dart';

class ficha extends StatefulWidget {
  const ficha({Key? key}) : super(key: key);

  @override
  State<ficha> createState() => _fichaState();
}

class _fichaState extends State<ficha> {
  bool fi = false;
  bool f2 = false;

  ExpansionPanelList getpaneList(){
    return ExpansionPanelList(
      expansionCallback: (panelIndex, isExpanded) {
        setState(() {
          if(panelIndex == 0){
            fi = !isExpanded;
          }
          if (panelIndex == 1){
            f2 = !isExpanded;
          }
        });
      },
      children: [
      ExpansionPanel(
          isExpanded: fi,
          headerBuilder: (_, isExpanded){
           return ListTile(
          title: Center(child: Text("A Pagar - R\$ 59.711,52")),
        );
      },

        body: Row(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            Column(
              children: [
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("17M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("18M",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("19M",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("20M",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("21M",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("22M",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("23M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("24M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("25M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("26M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("27M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3IT",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("28M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("29M",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Parcela",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("30M",
                    style: TextStyle(color: Colors.black)
                ),

              ],
            ),
            Column(
              children: [
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000.00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000.00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("15.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("Valor Original",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.000,00",
                    style: TextStyle(color: Colors.black)
                ),

              ],
            ),
            Column(
              children: [
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.482,37",
                    style: TextStyle(color: Colors.black),
                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.482.37",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.642,01",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.710,46",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.791,67",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.852,09",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("2.934,85",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3.002,98",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3.078,33",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3.167,06",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3.254,76",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("17.892,00",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3.349,16",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3.444,60",
                    style: TextStyle(color: Colors.black)

                ),
                SizedBox(height: 10.0),
                Text("Valor Atualizado",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("3.549,03",
                    style: TextStyle(color: Colors.black)

                ),

              ],
            ),
            Column(
              children: [
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/08/2022",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/09/2023",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/10/2023",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/11/2023",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/12/2023",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/01/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/02/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/03/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/04/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/05/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/06/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/07/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/07/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/08/2024",
                    style: TextStyle(color: Colors.black)
                ),
                SizedBox(height: 10.0),
                Text("DT. Vencimento:",
                  style: TextStyle(color:Colors.yellow[900], fontSize: 12.0,
                  ),
                ),
                SizedBox(height: 5.0),
                Text("03/09/2024",
                    style: TextStyle(color: Colors.black)
                )
              ],
            ),

          ],
        ),

      ),
        ExpansionPanel(
            isExpanded: f2,
            headerBuilder: (_, isExpanded){
              return ListTile(
                  title: Center(child: Text("Pagas - R\$ 389.765,13 "),
                  ),
              );
            },
            body: SafeArea(
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  //parte1
                  Column(
                    children: [
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("1S",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("1M",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2M",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("3M",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("4M",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("5M",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("1IT",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("6M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("7M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("8M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("9M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("10M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("11M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("12M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("13M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("14M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("15M",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("Parcela",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("16M",
                          style: TextStyle(color: Colors.black)
                      ),

                    ],
                  ),
                  Column(
                    children: [
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("323,000,00",
                        style: TextStyle(color: Colors.black),
                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("15.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("15.000,00",
                          style: TextStyle(color: Colors.black)

                      ),

                    ],
                  ),
                  Column(
                    children: [
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.5,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("323,000,00",
                        style: TextStyle(color: Colors.black),
                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.000,00",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.006,32",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.017,05",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.034,13",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.056,82",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("15.240,01",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.077,12",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.102,24",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.140,77",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.180,25",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.235,01",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.291,84",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.335,99",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.370,54",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.413,84",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Pago",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("2.450,83",
                          style: TextStyle(color: Colors.black)

                      ),
                      SizedBox(height: 10.0),
                      Text("Valor Atualizado",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("16.340,19",
                          style: TextStyle(color: Colors.black)

                      ),
                    ],
                  ),
                  Column(
                    children: [
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("01/03/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/03/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/04/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/05/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/06/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/07/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/08/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/09/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/10/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/11/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/12/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/01/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/03/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/04/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/05/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/06/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/07/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Vencimento:",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/07/2023",
                          style: TextStyle(color: Colors.black)
                      )

                    ],
                  ),
                  Column(
                    children: [
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("01/03/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/03/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/04/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/05/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/06/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/07/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/07/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/08/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/09/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/10/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/11/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/12/2022",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/01/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/03/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/03/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/04/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/05/2023",
                          style: TextStyle(color: Colors.black)
                      ),
                      SizedBox(height: 10.0),
                      Text("DT. Pagamento",
                        style: TextStyle(color:Colors.yellow[900], fontSize: 10.0,
                        ),
                      ),
                      SizedBox(height: 5.0),
                      Text("03/06/2023",
                          style: TextStyle(color: Colors.black)
                      ),

                    ],
                  ),

                ],
              ),
            )
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        backgroundColor: Colors.white,
        body: ListView(
          children: [
            Container(
              padding: EdgeInsets.all(10),
                child: Center(
                  child: Text(
                    "Ficha Financeira",
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 30.0,
                        fontFamily: "Pacifico-Regular",
                        fontWeight: FontWeight.bold
                    ),
                  ),
                ),
              decoration: BoxDecoration(
                  border: Border(
                    bottom: BorderSide(width: 2.0, color: Colors.black12),
                  )),

      ),
            SizedBox(
              height: 30,
            ),
            getpaneList(),
            SizedBox(height: 50),

          ],
        ),

          ),
        );
  }
}
