---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/cesarborman/GitHub/cfcasafeita/.dart_tool/flutter_build/38c7757af0c930ec6f9c46d8c218f40a/arm64/App.framework/App'
relocations:     []
...
